# Generated by Django 2.2.8 on 2020-04-27 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects_add_documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_icon', models.FileField(upload_to='proje/')),
                ('project_banner', models.FileField(upload_to='proje/')),
                ('documentation', models.FileField(upload_to='proje/')),
                ('intraction_document', models.FileField(upload_to='proje/')),
                ('other_reports', models.FileField(upload_to='proje/')),
                ('upload_video', models.FileField(upload_to='proje/')),
                ('screenshort_1', models.FileField(upload_to='proje/')),
                ('screenshort_2', models.FileField(upload_to='proje/')),
                ('screenshort_3', models.FileField(upload_to='proje/')),
                ('screenshort_4', models.FileField(upload_to='proje/')),
                ('screenshort_5', models.FileField(upload_to='proje/')),
                ('screenshort_6', models.FileField(upload_to='proje/')),
                ('project_add', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(auto_now=True, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdocumentsuser', to=settings.AUTH_USER_MODEL)),
                ('deleted_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletedocumentsuser', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updatedocumentsuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=1000)),
                ('Technology', models.CharField(max_length=500)),
                ('Documents', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('Relevant_Project', models.CharField(max_length=100)),
                ('Support', models.CharField(max_length=100)),
                ('Cost', models.DecimalField(decimal_places=15, max_digits=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_user', models.PositiveIntegerField(blank=True, null=True)),
                ('deleted', models.DateTimeField(auto_now=True, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
