# Generated by Django 2.2.8 on 2020-04-23 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.PositiveIntegerField()),
                ('skill', models.CharField(max_length=200)),
                ('cover_letter', models.FileField(max_length=254, upload_to='cover_letter/')),
                ('tagline', models.CharField(max_length=100)),
                ('Nationality', models.CharField(max_length=30)),
                ('image', models.ImageField(max_length=254, upload_to='profile_image/')),
                ('introduce_yourself', models.TextField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
